version: '3'

services:
  mysql:
    image: hj3ric/mysql:v1
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: asd123
      MYSQL_DATABASE: drupal_db
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: asdf1234
    volumes:
      - mysql_data:/var/lib/mysql

  drupal:
    image: hj3ric/drupal:v1
    container_name: drupal
    ports:
      - "8080:80"
    environment:
      DRUPAL_DB_HOST: mysql_container
      DRUPAL_DB_NAME: drupal_db
      DRUPAL_DB_USER: drupal_user
      DRUPAL_DB_PASSWORD: asdf1234
    depends_on:
      - mysql

volumes:
  mysql_data: